# Generated by Django 4.2.3 on 2023-08-01 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 47, 40, 454722)),
        ),
    ]
