# Generated by Django 4.2.3 on 2023-08-01 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
